apiVersion: v1
kind: Service
metadata:
  name: qwen3-06b-vllm
  namespace: token-labs
  labels:
    llm-d.ai/model: qwen3-0.6b
spec:
  selector:
    llm-d.ai/model: qwen3-0.6b
    llm-d.ai/role: decode
  ports:
    - name: http
      port: 8000
      targetPort: 8000
