apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-ai-gateway
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: envoy-ai-gateway-system
  # AI Gateway controller must start after Envoy Gateway is ready
  dependsOn:
    - name: envoy-gateway
  chart:
    spec:
      chart: ai-gateway-helm
      version: "v0.5.0"
      sourceRef:
        kind: HelmRepository
        name: envoyproxy
        namespace: flux-system
      interval: 12h
