apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - alertmanager-receiver.yaml
  # Apply secret.yaml manually — it's gitignored
