---
apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: gateway-helm
      version: "v1.6.x"
      sourceRef:
        kind: HelmRepository
        name: envoyproxy
        namespace: flux-system
      interval: 5m
  targetNamespace: envoy-gateway-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: gateway-api-crds
      namespace: flux-system
  values:
    createNamespace: false
    config:
      envoyGateway:
        gateway:
          controllerName: gateway.envoyproxy.io/gatewayclass-controller
        provider:
          type: Kubernetes
        extensionApis:
          enableEnvoyPatchPolicy: true
