---
apiVersion: v1
kind: Namespace
metadata:
  name: kuadrant-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kuadrant-operator
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: kuadrant-operator
      version: "0.11.x"
      sourceRef:
        kind: HelmRepository
        name: kuadrant
        namespace: flux-system
      interval: 5m
  targetNamespace: kuadrant-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: gateway-api-crds
      namespace: flux-system
  values:
    operator:
      replicas: 1
    authorino:
      enabled: true
      replicas: 1
    limitador:
      enabled: true
      replicas: 1
      rateLimiting:
        storage: redis
      redis:
        enabled: true
