apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn
  - nvidia-gpu-operator
  - nvidia-dra-driver
  - envoy-gateway
  - envoy-ai-gateway
  - kuadrant
  - kube-prometheus-stack
