apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - loki-configmap.yaml
  - loki-pvc.yaml
  - loki-deployment.yaml
  - promtail-rbac.yaml
  - promtail-configmap.yaml
  - promtail-daemonset.yaml
  - grafana-datasource-loki.yaml
