---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoyproxy
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://gateway.envoyproxy.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kuadrant
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kuadrant.io/helm-charts
