apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: llm-d-infra
  namespace: flux-system
spec:
  interval: 12h
  url: https://llm-d-incubation.github.io/llm-d-infra/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: llm-d-modelservice
  namespace: flux-system
spec:
  interval: 12h
  url: https://llm-d-incubation.github.io/llm-d-modelservice/
