---
# Source: hindsight/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hindsight
  labels:
    helm.sh/chart: hindsight-0.9.0
    app.kubernetes.io/name: hindsight
    app.kubernetes.io/instance: hindsight
    app.kubernetes.io/version: "0.9.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: hindsight/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hindsight-secret
  labels:
    helm.sh/chart: hindsight-0.9.0
    app.kubernetes.io/name: hindsight
    app.kubernetes.io/instance: hindsight
    app.kubernetes.io/version: "0.9.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  HINDSIGHT_API_LLM_API_KEY: "bG9jYWwtdmxsbQ=="
  HINDSIGHT_API_TENANT_API_KEY: "aHNrX3NlbGZob3N0X2RmN2FiMjE1ZDk5YTU4NjFhM2ZlOTJkNmVmZjhhNWMyYzJjNDkyYWQ2YzllZGY4Yw=="
---
# Source: hindsight/templates/api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hindsight-api
  labels:
    helm.sh/chart: hindsight-0.9.0
    app.kubernetes.io/name: hindsight
    app.kubernetes.io/instance: hindsight
    app.kubernetes.io/version: "0.9.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: hindsight
    app.kubernetes.io/instance: hindsight
    app.kubernetes.io/component: api
---
# Source: hindsight/templates/controlplane-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hindsight-control-plane
  labels:
    helm.sh/chart: hindsight-0.9.0
    app.kubernetes.io/name: hindsight
    app.kubernetes.io/instance: hindsight
    app.kubernetes.io/version: "0.9.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: hindsight
    app.kubernetes.io/instance: hindsight
    app.kubernetes.io/component: control-plane
---
# Source: hindsight/templates/postgresql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hindsight-postgresql
  labels:
    helm.sh/chart: hindsight-0.9.0
    app.kubernetes.io/name: hindsight
    app.kubernetes.io/instance: hindsight
    app.kubernetes.io/version: "0.9.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    app.kubernetes.io/name: hindsight
    app.kubernetes.io/instance: hindsight
    app.kubernetes.io/component: postgresql
---
# Source: hindsight/templates/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hindsight-api
  labels:
    helm.sh/chart: hindsight-0.9.0
    app.kubernetes.io/name: hindsight
    app.kubernetes.io/instance: hindsight
    app.kubernetes.io/version: "0.9.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hindsight
      app.kubernetes.io/instance: hindsight
      app.kubernetes.io/component: api
  template:
    metadata:
      annotations:
        checksum/secret: 77739ec81fd42dd913a1edf19fc625e28bbe566b57901ef9d8fb8bd1637941d7
      labels:
        app.kubernetes.io/name: hindsight
        app.kubernetes.io/instance: hindsight
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: hindsight
      securityContext:
        fsGroup: 1000
      containers:
      - name: api
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
        image: "ghcr.io/vectorize-io/hindsight-api:0.9.0"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8888
          protocol: TCP
        env:
        - name: HINDSIGHT_API_DATABASE_URL
          value: "postgresql://hindsight:dd9d2b18cb2e08ccea6423ae9a57c756f01620c06141b631@hindsight-postgresql:5432/hindsight"
        - name: HINDSIGHT_API_PORT
          value: "8888"
        - name: HINDSIGHT_API_ENABLE_DOCUMENT_EXPORT_API
          value: "true"
        - name: HINDSIGHT_API_ENABLE_DOCUMENT_IMPORT_API
          value: "true"
        - name: HINDSIGHT_API_LLM_BASE_URL
          value: "http://hindsight-llm.hindsight.svc.cluster.local:8000/v1"
        - name: HINDSIGHT_API_LLM_EXTRA_BODY
          value: "{\"chat_template_kwargs\":{\"enable_thinking\":false}}"
        - name: HINDSIGHT_API_LLM_MAX_CONCURRENT
          value: "2"
        - name: HINDSIGHT_API_LLM_MODEL
          value: "Qwen/Qwen3.6-27B-FP8"
        - name: HINDSIGHT_API_LLM_PROVIDER
          value: "openai"
        - name: HINDSIGHT_API_LLM_STRICT_SCHEMA
          value: "true"
        - name: HINDSIGHT_API_LLM_TIMEOUT
          value: "600"
        - name: HINDSIGHT_API_TENANT_EXTENSION
          value: "hindsight_api.extensions.builtin.tenant:ApiKeyTenantExtension"
        - name: HINDSIGHT_API_WORKER_ID
          value: "hindsight-api"
        - name: HINDSIGHT_API_LLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: hindsight-secret
              key: HINDSIGHT_API_LLM_API_KEY
        - name: HINDSIGHT_API_TENANT_API_KEY
          valueFrom:
            secretKeyRef:
              name: hindsight-secret
              key: HINDSIGHT_API_TENANT_API_KEY
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: 500m
            memory: 2Gi
      nodeSelector:
        kubernetes.io/hostname: controller
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
---
# Source: hindsight/templates/controlplane-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hindsight-control-plane
  labels:
    helm.sh/chart: hindsight-0.9.0
    app.kubernetes.io/name: hindsight
    app.kubernetes.io/instance: hindsight
    app.kubernetes.io/version: "0.9.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hindsight
      app.kubernetes.io/instance: hindsight
      app.kubernetes.io/component: control-plane
  template:
    metadata:
      annotations:
        checksum/secret: 77739ec81fd42dd913a1edf19fc625e28bbe566b57901ef9d8fb8bd1637941d7
      labels:
        app.kubernetes.io/name: hindsight
        app.kubernetes.io/instance: hindsight
        app.kubernetes.io/component: control-plane
    spec:
      serviceAccountName: hindsight
      securityContext:
        fsGroup: 1000
      containers:
      - name: control-plane
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
        image: "ghcr.io/vectorize-io/hindsight-control-plane:0.9.0"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: HINDSIGHT_CP_DATAPLANE_API_URL
          value: "http://hindsight-api:8888"
        - name: HINDSIGHT_CP_ACCESS_KEY
          value: "e2b2603aa3a0b6355066b7a2da613d495d48e9fbac93ea2e"
        - name: HINDSIGHT_CP_DATAPLANE_API_KEY
          value: "hsk_selfhost_df7ab215d99a5861a3fe92d6eff8a5c2c2c492ad6c9edf8c"
        - name: HINDSIGHT_CP_HOSTNAME
          value: "0.0.0.0"
        - name: HINDSIGHT_CP_PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          tcpSocket:
            port: 3000
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          tcpSocket:
            port: 3000
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
      nodeSelector:
        kubernetes.io/hostname: controller
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
---
# Source: hindsight/templates/postgresql-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hindsight-postgresql
  labels:
    helm.sh/chart: hindsight-0.9.0
    app.kubernetes.io/name: hindsight
    app.kubernetes.io/instance: hindsight
    app.kubernetes.io/version: "0.9.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgresql
spec:
  serviceName: hindsight-postgresql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hindsight
      app.kubernetes.io/instance: hindsight
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hindsight
        app.kubernetes.io/instance: hindsight
        app.kubernetes.io/component: postgresql
    spec:
      containers:
      - name: postgresql
        image: "ankane/pgvector:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - name: postgresql
          containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: "hindsight"
        - name: POSTGRES_PASSWORD
          value: "dd9d2b18cb2e08ccea6423ae9a57c756f01620c06141b631"
        - name: POSTGRES_DB
          value: "hindsight"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - hindsight
            - -d
            - hindsight
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - hindsight
            - -d
            - hindsight
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "hindsight-local"
      resources:
        requests:
          storage: 50Gi
---
# Source: hindsight/templates/pdb.yaml
---

