---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache-qwen3-0.6b-spark-01
  namespace: token-labs
  annotations:
    volume.kubernetes.io/selected-node: spark-01
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-model-cache
  resources:
    requests:
      storage: 20Gi
