---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache-deepseek-r1-32b-spark-01
  namespace: token-labs
  annotations:
    volume.kubernetes.io/selected-node: spark-01
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-model-cache
  resources:
    requests:
      storage: 300Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache-deepseek-r1-32b-spark-02
  namespace: token-labs
  annotations:
    volume.kubernetes.io/selected-node: spark-02
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-model-cache
  resources:
    requests:
      storage: 300Gi
